---
abstract: 'Get rough sizes for the memory useage of perl'
author:
  - 'All code taken from mod_perl is copyright the authors llisted in'
build_requires:
  ExtUtils::MakeMaker: 6.36
  Test::More: 0.88
configure_requires:
  ExtUtils::MakeMaker: 6.36
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.06'
license: apache2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: Devel::InterpreterSize
name: Devel-InterpreterSize
no_index:
  directory:
    - inc
    - t
requires:
  BSD::Resource: 0
  Class::Load: 0
resources:
  license: http://apache.org/licenses/LICENSE-2.0
version: 0.01
